//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laba_Biznes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel_comment
    {
        public int id { get; set; }
        public int Hotel_id { get; set; }
        public string Comment { get; set; }
        public string Author { get; set; }
        public System.DateTime Creation_Date { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
